apiVersion: v1
kind: Namespace
metadata:
  name: test-infrastructure
  labels:
    name: test-infrastructure
    environment: test
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  namespace: test-infrastructure
data:
  environment: "kind"
  test-mode: "true"
  message: "Hello from test infrastructure!"
