apiVersion: v1
kind: Namespace
metadata:
  name: test-apps
  labels:
    name: test-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
  namespace: test-apps
  labels:
    app: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-nginx
  namespace: test-apps
  labels:
    app: test-nginx
spec:
  selector:
    app: test-nginx
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
